"""Revision 2 of the v0.51 specification text after the external review (kept for provenance).
Replaces whole section blocks of v051_text.py between marker comments and fixes a few sentences in §5."""
import os
import re

H = os.path.dirname(os.path.abspath(__file__))
p = os.path.join(H, "v051_text.py")
s = open(p, encoding="utf-8").read()


def rep(a, b, n=1):
    global s
    assert s.count(a) == n, (a[:80], s.count(a))
    s = s.replace(a, b)


def block(start, end, new):
    global s
    i, j = s.index(start), s.index(end)
    s = s[:i] + new + s[j:]


# ------------------------------------------------------------------ diagrams, names, references
rep('d4_act="Ativo", d4_act2="contribui para ŷ_S", d4_evi="Removido", d4_evi2="alarme de mudança",',
    'd4_act="Ativo", d4_act2="contribui para ŷ_S", d4_evi="Removido", d4_evi2="perda de utilidade",')
rep('d4_act="Active", d4_act2="contributes to ŷ_S", d4_evi="Evicted", d4_evi2="change alarm",',
    'd4_act="Active", d4_act2="contributes to ŷ_S", d4_evi="Evicted", d4_evi2="loss of usefulness",')
rep('d4_sub="Cada transição é uma decisão estatística com taxa de erro controlada",',
    'd4_sub="Promoção: teste com erro tipo I controlado por episódio. Remoção: CUSUM com aluguel (sem garantia formal de ARL)",')
rep('d4_sub="Every transition is a statistical decision with a controlled error rate",',
    'd4_sub="Promotion: test with type-I error controlled per episode. Eviction: CUSUM with rent (no formal ARL guarantee)",')
rep('d5_ref="NLinear = 1", d5_note="Chronos-2 com covariáveis só se aplica às 4 séries multivariadas (razão calculada nessas 4).",',
    'd5_ref="NLinear = 1", d5_note="Chronos-2 c/ covariáveis: só as 4 séries multivariadas. Airline (MLE): análise pós-hoc, 9 séries (falha de memória com s = 144).",')
rep('d5_ref="NLinear = 1", d5_note="Chronos-2 with covariates only applies to the 4 multivariate series (ratio computed on those 4).",',
    'd5_ref="NLinear = 1", d5_note="Chronos-2 w/ covariates: the 4 multivariate series only. Airline (MLE): post-hoc analysis, 9 series (out of memory with s = 144).",')
rep('"CHRONOS2_COV": "Chronos-2 c/ covariáveis"},',
    '"CHRONOS2_COV": "Chronos-2 c/ covariáveis", "M_ONLY": "Só M (memória sozinha)", "AIRLINE": "Airline (MLE, pós-hoc)"},')
rep('"CHRONOS2_COV": "Chronos-2 w/ covariates"},',
    '"CHRONOS2_COV": "Chronos-2 w/ covariates", "M_ONLY": "M only (memory alone)", "AIRLINE": "Airline (MLE, post-hoc)"},')
rep('    "Rissanen, J. (1978).', '    "Seabold, S., Perktold, J. (2010). statsmodels: econometric and statistical modeling with Python. <em>Proc. 9th Python in Science Conference</em>.",\n    "Rissanen, J. (1978).')

# ------------------------------------------------------------------ §5 sentence fixes
rep("a probabilidade de uma promoção falsa em qualquer instante é ≤ α/p por candidato.",
    "a probabilidade de uma promoção falsa em qualquer instante é ≤ α/p por candidato <em>e por episódio de teste</em>. O controle vale por teste, não para o fluxo inteiro: como candidatos podem ser retestados com estatística nova, promoções falsas podem se acumular em fluxos muito longos (a taxa empírica está na §11).")
rep("the probability of a false promotion at any time is ≤ α/p per candidate.",
    "the probability of a false promotion at any time is ≤ α/p per candidate <em>and per test episode</em>. The control holds per test, not for the whole stream: since candidates can be re-tested with fresh statistics, false promotions can accumulate over very long streams (the empirical rate is in §11).")
rep("sem aluguel, o tempo médio até um alarme falso é ≥ e<sup>h</sup> (Lorden, 1971; Moustakides, 1986). Cada remoção é um <strong>alarme de mudança estrutural</strong>.",
    "<em>sem</em> aluguel, o tempo médio até um alarme falso seria ≥ e<sup>h</sup> (Lorden, 1971; Moustakides, 1986). <strong>O aluguel quebra essa garantia:</strong> ele empurra o CUSUM na direção da remoção, de modo que uma remoção significa \"o átomo deixou de pagar o seu custo\", seja por mudança real, seja por contribuição pequena. Por isso as remoções são tratadas como <strong>sinais de perda de utilidade</strong>, não como alarmes com taxa de erro controlada (taxa empírica na §11).")
rep("without rent, the mean time to a false alarm is ≥ e<sup>h</sup> (Lorden, 1971; Moustakides, 1986). Every eviction is a <strong>structural change alarm</strong>.",
    "<em>without</em> rent, the mean time to a false alarm would be ≥ e<sup>h</sup> (Lorden, 1971; Moustakides, 1986). <strong>The rent breaks that guarantee:</strong> it pushes the CUSUM towards eviction, so an eviction means \"the atom stopped paying for itself\", whether because of a real change or because of a small contribution. Evictions are therefore treated as <strong>loss-of-usefulness signals</strong>, not as alarms with a controlled error rate (empirical rate in §11).")
rep("então o controle de erro dos testes continua válido.", "então o controle de erro de cada teste continua válido.")
rep("so the tests\\' error control remains valid.", "so each test\\'s error control remains valid.")
rep("que era a causa da instabilidade de versões anteriores (§10)", "que era a causa da instabilidade de versões anteriores (§13)")
rep("which caused the instability of earlier versions (§10)", "which caused the instability of earlier versions (§13)")

# ------------------------------------------------------------------ §1 executive summary (whole block)
block("        # ------------------------------------------------------------ 1 executive summary + TOC",
      "        # ------------------------------------------------------------ 2 what / what for", r'''        # ------------------------------------------------------------ 1 executive summary + TOC
        toc = [T("Sumário executivo", "Executive summary"), T("O que é a LEBRE, para que serve e qual é a premissa", "What LEBRE is, what it is for and its premise"),
               T("Princípios de projeto", "Design principles"), T("Visão geral da arquitetura", "Architecture overview"),
               T("Formulação matemática", "Mathematical formulation"), T("Fluxo de um passo e causalidade", "One step and causality"),
               T("Custo computacional", "Computational cost"), T("Observabilidade e explicabilidade", "Observability and explainability"),
               T("Validação empírica e rigor metodológico", "Empirical validation and methodological rigour"),
               T("LEBRE contra a memória sozinha e contra clássicos fortes", "LEBRE versus the memory alone and strong classical baselines"),
               T("Garantias estatísticas na prática", "Statistical guarantees in practice"),
               T("O que este documento demonstra e o que não demonstra", "What this document demonstrates and what it does not"),
               T("Evolução da arquitetura e lições", "Evolution of the architecture and lessons"),
               T("Limites e afirmações que não fazemos", "Limits and claims we do not make"),
               T("Parâmetros", "Parameters"), T("Referências", "References")]
        tl = "".join(f'<li class="toc-item"><span class="toc-title">{i + 1}. {t}</span><span class="toc-page">§{i + 1}</span></li>' for i, t in enumerate(toc))
        sm = N["ph_summ"]
        out.append(f"""<div class="page-break"></div><h1>1. {toc[0]}</h1>
<p>{T("A <strong>LEBRE</strong> é um previsor <strong>online</strong> de séries temporais: a cada passo ela recebe uma observação, prevê o próximo valor, aprende com o erro e segue adiante, sem reprocessar o passado. A versão <strong>v0.51</strong> tem quatro peças: um <strong>especialista estrutural</strong> (dinâmica guiada por entradas, com descoberta de estrutura por testes estatísticos), um <strong>especialista de memória</strong> (nível e ciclo do próprio alvo), um <strong>combinador</strong> por média dinâmica de modelos e um <strong>intervalo de predição</strong> calibrado online.",
"<strong>LEBRE</strong> is an <strong>online</strong> time-series forecaster: at every step it receives an observation, predicts the next value, learns from the error and moves on, without re-processing the past. Version <strong>v0.51</strong> has four parts: a <strong>structural expert</strong> (input-driven dynamics, with structure discovered by statistical tests), a <strong>memory expert</strong> (level and cycle of the target itself), a <strong>combiner</strong> based on dynamic model averaging, and an online-calibrated <strong>prediction interval</strong>.")}</p>
<div class="alert alert-warning"><strong>{T("Premissa", "Premise")}:</strong> {T("a LEBRE <strong>não</strong> pretende ser o modelo mais preciso. O objetivo é oferecer <strong>desempenho bom e competitivo</strong> com <strong>custo computacional mínimo</strong> (dimensionado para dispositivos embarcados), <strong>sem ajuste por série</strong> e com <strong>explicabilidade e observabilidade</strong> de cada previsão. Modelos de fundação e modelos clássicos ajustados série a série podem ser mais precisos; este documento mostra onde e por quanto.",
"LEBRE does <strong>not</strong> aim to be the most accurate model. Its goal is <strong>good, competitive accuracy</strong> at <strong>minimal computational cost</strong> (sized for embedded devices), <strong>without per-series tuning</strong>, and with <strong>explainability and observability</strong> of every forecast. Foundation models and classical models fitted series by series can be more accurate; this document shows where and by how much.")}</div>
<div class="alert alert-info"><strong>{T("Resultado principal (avaliação pré-registrada em 10 séries reais nunca usadas no desenvolvimento, 5 delas brasileiras):", "Main result (pre-registered evaluation on 10 real series never used during development, 5 of them Brazilian):")}</strong>
{T("melhor modelo entre os não-fundação avaliados, com erro", "best of the evaluated non-foundation models, with error")} {n(p2["C1_geo_vs_NLinear"], 2)}× {T("o do NLinear online calibrado", "that of the calibrated online NLinear")};
{n(p2["C3_geo_vs_best_chronos"], 2)}× {T("o do Chronos-2 (modelo de fundação), com custo ~10⁶–10⁷ vezes menor", "that of Chronos-2 (foundation model), at ~10⁶–10⁷ times lower cost")};
{n(ch.loc["LEBRE_V051", "fp"], 0)} {T("operações por passo em média (pico", "operations per step on average (peak")} {n(p2["B_heldout_max_peak"], 0)}); ~{n(ch.loc["LEBRE_V051", "mem"] / 1024, 1)} KB {T("de estado", "of state")};
{T("variação máxima de", "maximum variation of")} {n(p2["S1_max"], 3)}× {T("entre pontos de partida", "across start points")}.</div>
<div class="alert alert-danger"><strong>{T("O que a crítica externa e as análises pós-hoc mostraram (§10–§12):", "What the external review and the post-hoc analyses showed (§10–§12):")}</strong>
{T(f"nas séries reais, <strong>quase todo o resultado vem do especialista de memória</strong>. A memória sozinha fica a {n(sm[('held', 'M_ONLY')]['geo'], 3)}× da LEBRE completa e dá resultado idêntico em {sm[('held', 'M_ONLY')]['same']} de 10 séries. Um modelo airline clássico <strong>ajustado série a série por máxima verossimilhança</strong> é ~{n(100 * (1 - sm[('held', 'AIRLINE')]['geo']), 0)}–{n(100 * (1 - sm[('held05', 'AIRLINE')]['geo']), 0)}% mais preciso que a LEBRE. O que a LEBRE acrescenta à memória é universalidade (sistemas guiados por entradas), descoberta estrutural nomeada, ausência de ajuste por série e intervalos calibrados; a parte estrutural ainda não tem evidência em séries reais genuinamente guiadas por entradas.",
f"on real series, <strong>almost all of the result comes from the memory expert</strong>. The memory alone is at {n(sm[('held', 'M_ONLY')]['geo'], 3)}× the full LEBRE and gives identical results on {sm[('held', 'M_ONLY')]['same']} of 10 series. A classical airline model <strong>fitted series by series by maximum likelihood</strong> is ~{n(100 * (1 - sm[('held', 'AIRLINE')]['geo']), 0)}–{n(100 * (1 - sm[('held05', 'AIRLINE')]['geo']), 0)}% more accurate than LEBRE. What LEBRE adds to the memory is universality (input-driven systems), named structure discovery, no per-series tuning and calibrated intervals; the structural part still has no evidence on real, genuinely input-driven series.")}</div>
<h2>{T("Guia do documento", "Document guide")}</h2><ul class="toc-list">{tl}</ul>""")

''')

# ------------------------------------------------------------------ §2 what / premise (whole block)
block("        # ------------------------------------------------------------ 2 what / what for",
      "        # ------------------------------------------------------------ 3 principles", r'''        # ------------------------------------------------------------ 2 what / what for
        out.append(f"""<div class="page-break"></div><h1>2. {toc[1]}</h1>
<h2>{T("O problema", "The problem")}</h2>
<p>{T("Muitos sistemas reais produzem medições em fluxo contínuo — consumo de energia, geração eólica e solar, vazão, qualidade do ar, sensores industriais, câmbio — e precisam de uma previsão do próximo valor <em>no próprio dispositivo</em>, com memória e energia escassas, sem GPU e sem a possibilidade de treinar offline com grandes históricos. Há três obstáculos: (i) os modelos modernos mais precisos (transformers e modelos de fundação) exigem centenas de megabytes e bilhões de operações por previsão; (ii) modelos estatísticos clássicos são baratos, mas precisam ser ajustados série a série; (iii) em aplicações críticas, uma previsão sem explicação e sem incerteza quantificada tem pouco valor operacional.",
"Many real systems produce measurements as a continuous stream — energy load, wind and solar generation, flow, air quality, industrial sensors, exchange rates — and need a forecast of the next value <em>on the device itself</em>, with scarce memory and energy, no GPU and no possibility of offline training on large histories. There are three obstacles: (i) the most accurate modern models (transformers and foundation models) require hundreds of megabytes and billions of operations per forecast; (ii) classical statistical models are cheap but must be fitted series by series; (iii) in critical applications, a forecast without explanation and without quantified uncertainty has little operational value.")}</p>
<h2>{T("A premissa", "The premise")}</h2>
<p>{T("A LEBRE <strong>não compete para ser o modelo mais preciso</strong>. Ela é projetada para ocupar um ponto específico do compromisso entre precisão, custo e transparência: <strong>desempenho competitivo</strong> (no nível de modelos modernos leves), <strong>custo mínimo</strong> (centenas de operações por passo e poucos KB), <strong>nenhum ajuste por série</strong> (as mesmas constantes em qualquer fluxo) e <strong>explicabilidade e observabilidade</strong> de cada previsão. Perder alguns pontos percentuais de precisão para um modelo de fundação ou para um modelo clássico ajustado série a série é aceitável dentro dessa premissa; perder a competitividade, o custo baixo ou a transparência, não.",
"LEBRE <strong>does not compete to be the most accurate model</strong>. It is designed to occupy a specific point of the accuracy–cost–transparency trade-off: <strong>competitive accuracy</strong> (at the level of modern lightweight models), <strong>minimal cost</strong> (hundreds of operations per step and a few KB), <strong>no per-series tuning</strong> (the same constants on any stream), and <strong>explainability and observability</strong> of every forecast. Losing a few percentage points of accuracy to a foundation model or to a classical model fitted series by series is acceptable within this premise; losing competitiveness, low cost or transparency is not.")}</p>
<h2>{T("O que a LEBRE faz", "What LEBRE does")}</h2>
<ul><li>{T("<strong>Aprende online, a cada passo</strong>, sem fase de treino separada e sem calibração por série.", "<strong>Learns online, at every step</strong>, with no separate training phase and no per-series calibration.")}</li>
<li>{T("<strong>Funciona em dois tipos de problema</strong>: séries guiadas pela própria memória (sazonalidade, nível) e sistemas guiados por entradas (atrasos, estados ocultos), decidindo sozinha qual hipótese vale a cada momento.", "<strong>Works on two kinds of problem</strong>: series driven by their own memory (seasonality, level) and systems driven by inputs (delays, hidden states), deciding by itself which hypothesis holds at each moment.")}</li>
<li>{T("<strong>Decompõe cada previsão</strong> em parcelas nomeadas e <strong>registra</strong> quando e por que cada estrutura entrou ou saiu do modelo.", "<strong>Decomposes every forecast</strong> into named contributions and <strong>logs</strong> when and why each structure entered or left the model.")}</li>
<li>{T("<strong>Informa a própria incerteza</strong> com um intervalo de 90% calibrado online.", "<strong>Reports its own uncertainty</strong> with an online-calibrated 90% interval.")}</li>
<li>{T("<strong>Custa ~100–150 operações de ponto flutuante por passo</strong> e ~1,3 KB de estado. Esse orçamento é compatível com microcontroladores, mas a execução em hardware embarcado <strong>não foi verificada</strong>, e FP não mede energia.", "<strong>Costs ~100–150 floating-point operations per step</strong> and ~1.3 KB of state. This budget is compatible with microcontrollers, but execution on embedded hardware has <strong>not been verified</strong>, and FP does not measure energy.")}</li></ul>
<h2>{T("Para que serve (casos de uso típicos)", "What it is for (typical use cases)")}</h2>
<p>{T("Previsão de curto prazo embarcada em medidores e controladores de energia; monitoramento de geração renovável; sensores industriais; fluxos de IoT; qualquer contexto em que a previsão precise ser barata, auditável, acompanhada de incerteza e em que não seja viável ajustar um modelo para cada série.",
"Embedded short-term forecasting in energy meters and controllers; monitoring of renewable generation; industrial sensors; IoT streams; any context where the forecast must be cheap, auditable, accompanied by uncertainty, and where fitting a model for each series is not viable.")}</p>
<h2>{T("O que a LEBRE não é", "What LEBRE is not")}</h2>
<p>{T("Não é um modelo de fundação nem um previsor de longo horizonte; não modela relações fortemente não lineares entre entradas e alvo (a classe é linear nos parâmetros); não afirma causalidade física (as explicações descrevem o modelo, isto é, relevância preditiva). O nome vem da família original de arquiteturas do projeto (<em>Lifecycle-governed Evidence-Based Resource Evolution</em>): estruturas entram e saem do modelo por evidência estatística, sob orçamento explícito de recursos.",
"It is not a foundation model nor a long-horizon forecaster; it does not model strongly non-linear input–target relations (the class is linear in the parameters); it does not claim physical causality (explanations describe the model, i.e. predictive relevance). The name comes from the project's original family of architectures (<em>Lifecycle-governed Evidence-Based Resource Evolution</em>): structures enter and leave the model by statistical evidence, under an explicit resource budget.")}</p>""")

''')

# ------------------------------------------------------------------ §8 observability: bullets + honesty paragraph
rep("<li>{T('<strong>Registro do ciclo de vida</strong>: quando e por que cada estrutura entrou ou saiu, com a evidência em nats; cada remoção é um alarme de mudança com taxa de alarme falso controlada.', '<strong>Lifecycle log</strong>: when and why each structure entered or left, with the evidence in nats; each eviction is a change alarm with a controlled false-alarm rate.')}</li>",
    "<li>{T('<strong>Registro do ciclo de vida</strong>: quando e por que cada estrutura entrou ou saiu, com a evidência em nats. Promoções têm erro tipo I controlado por episódio de teste; remoções são sinais de perda de utilidade, <em>sem</em> taxa de alarme falso garantida (§5.3, §11).', '<strong>Lifecycle log</strong>: when and why each structure entered or left, with the evidence in nats. Promotions have type-I error controlled per test episode; evictions are loss-of-usefulness signals, <em>without</em> a guaranteed false-alarm rate (§5.3, §11).')}</li>")
rep("<li>{T('<strong>Custo contabilizado</strong> por componente.', '<strong>Accounted cost</strong> per component.')}</li></ul>",
    """<li>{T('<strong>Custo contabilizado</strong> por componente.', '<strong>Accounted cost</strong> per component.')}</li></ul>
<div class="alert alert-info">{T('<strong>O que é e o que não é diferencial.</strong> A decomposição exata é uma propriedade trivial de qualquer modelo linear aditivo: é verdadeira e útil, mas não distingue a LEBRE. O que a LEBRE acrescenta é (i) a <em>seleção</em> das parcelas por evidência estatística, com nomes físicos (quais atrasos e qual estado latente importam), (ii) o registro auditável dessas decisões e (iii) o peso w<sub>S</sub>, que diz qual hipótese está valendo. Nas séries sazonais, em que a memória domina, a explicação real é simples: <em>último valor, corrigido pelo incremento sazonal típico desta fase</em> — como mostra o exemplo 1.', '<strong>What is and what is not a differentiator.</strong> Exact decomposition is a trivial property of any linear additive model: it is true and useful, but it does not distinguish LEBRE. What LEBRE adds is (i) the <em>selection</em> of the contributions by statistical evidence, with physical names (which delays and which latent state matter), (ii) the auditable log of those decisions and (iii) the weight w<sub>S</sub>, which tells which hypothesis holds. On seasonal series, where the memory dominates, the real explanation is simple: <em>last value, corrected by the typical seasonal increment of this phase</em> — as example 1 shows.')}</div>""")

# ------------------------------------------------------------------ §9 .. §16 (whole tail of the section function)
block("        # ------------------------------------------------------------ 9 validation",
      "        if P:\n            fix = lambda mm:", r'''        # ------------------------------------------------------------ 9 validation
        qn = lambda t: TASKS[t][0]
        order = sorted(mh.index, key=lambda t: int(qn(t)[1:]))
        best_ch = mh[["CHRONOS_BOLT_TINY", "CHRONOS_BOLT_SMALL", "CHRONOS2", "CHRONOS2_COV"]].min(axis=1)
        ph = N["ph"]; phh = ph[ph.src == "held"].set_index("task")
        mo = phh[phh.arm == "M_ONLY"].nmse; air = phh[phh.arm == "AIRLINE"].nmse
        rows_t = []
        for t in order:
            r = mh.loc[t]
            vals = [r.LEBRE_V051, mo[t], r.NLINEAR_ONLINE, r.DLINEAR_ONLINE, r.HOLT_WINTERS, best_ch[t], r.CTRL_PERSISTENCE]
            mn = min(vals[:6])
            cells = [f"<strong>{n(v, 4)}</strong>" if v == mn else n(v, 4) for v in vals]
            rows_t.append([qn(t), TASKS[t][1] if P else TASKS[t][2]] + cells + [n(ins.loc[t, "V051"], 3), n(cov[t], 3)])
        nonfm = [m for m in rank.index if not m.startswith("CHRONOS") and m not in ("LEBRE_V05", "LEBRE_V045", "LEBRE_V032")]
        fm = [m for m in rank.index if m.startswith("CHRONOS")]
        rk_all = [m for m in rank.index if m not in ("LEBRE_V05", "LEBRE_V045", "LEBRE_V032")]
        r2 = mh[rk_all].rank(axis=1, method="min").mean().sort_values()
        pos = r2.rank(method="min").astype(int)
        rk = [(f"{pos[m]}º" if P else str(pos[m]), MN.get(m, m), T("fundação", "foundation") if m in fm else T("online leve", "online lightweight"), n(v, 2)) for m, v in r2.items()]
        rows_ds = [(TASKS[t][0], TASKS[t][1] if P else TASKS[t][2], TASKS[t][4].split(" / ")[0 if P else 1] if "/" in TASKS[t][4] else TASKS[t][4],
                    TASKS[t][5], TASKS[t][6] or "—") for t in order]
        acc = [T("Critério", "Criterion"), T("Limiar", "Threshold"), T("Resultado", "Result")]
        crit = [(T("Custo médio por tarefa (interno d = 5; held-out d ≤ 6)", "Mean cost per task (internal d = 5; held-out d ≤ 6)"), "≤ 150 FP", f"{n(p1['B_internal_max_mean_fp'], 0)} / {n(p2['B_heldout_max_mean_fp'], 0)} ✔"),
                (T("Pico por passo", "Peak per step"), "≤ 500 FP", f"{n(p1['B_internal_max_peak'], 0)} / {n(p2['B_heldout_max_peak'], 0)} ✔"),
                (T("Interno: não piora contra o especialista estrutural sozinho (limite sup. 95%)", "Internal: no degradation vs the structural expert alone (upper 95%)"), "< +0,010" if P else "< +0.010", f"+{n(p1['I-1_upper95'], 4)} ✔"),
                (T("Cobertura interna do intervalo de 90%", "Internal 90% interval coverage"), "[0,88; 0,92]" if P else "[0.88, 0.92]", f"{n(p1['I-2_cov'], 3)} ✔"),
                (T("Fidelidade da explicação (erro relativo)", "Explanation fidelity (relative error)"), "≤ 1e−9", f"{p1['I-3_faith']:.0e} ✔"),
                (T("Held-out: razão contra NLinear", "Held-out: ratio vs NLinear"), "≤ 1,10" if P else "≤ 1.10", f"{n(p2['C1_geo_vs_NLinear'], 3)} ✔"),
                (T("Held-out: razão contra o melhor de NLinear, DLinear, Holt-Winters", "Held-out: ratio vs best of NLinear, DLinear, Holt-Winters"), "≤ 1,15" if P else "≤ 1.15", f"{n(p2['C2_geo_vs_best_modern_linear'], 3)} ✔"),
                (T("Held-out: razão contra a variante anterior com janela densa (~1000 FP)", "Held-out: ratio vs the previous dense-window variant (~1000 FP)"), "≤ 1,10" if P else "≤ 1.10", f"{n(p2['C4_geo_vs_V05'], 3)} ✔"),
                (T("Estabilidade entre 10 pontos de partida (mediana / máx.)", "Stability across 10 start points (median / max)"), "≤ 1,10 / ≤ 1,50" if P else "≤ 1.10 / ≤ 1.50", f"{n(p2['S1_median'], 3)} / {n(p2['S1_max'], 3)} ✔"),
                (T("Tarefas com cobertura em [0,85; 0,95]", "Tasks with coverage in [0.85, 0.95]"), "≥ 80%", f"{n(100 * p2['S2_frac'], 0)}% ✔"),
                (T("Divergências numéricas", "Numerical divergences"), "0", "0 ✔"),
                (T("Meta (não vinculante): razão contra o melhor Chronos", "Target (non-binding): ratio vs best Chronos"), "≤ 1,50" if P else "≤ 1.50", f"{n(p2['C3_geo_vs_best_chronos'], 3)} ✔")]
        sk = N["skill"]; rmae = N["relmae"]
        phs = ph[ph.src == "held"].pivot_table(index="task", columns="arm", values="skill")
        phm = ph[ph.src == "held"].pivot_table(index="task", columns="arm", values="rel_mae")
        def srow(name, sv, mv):
            sv = sv.dropna(); mv = mv.dropna()
            return (name, n(float(sv.median()), 3), f"{int((sv > 0).sum())}/{len(sv)}", n(float(mv.median()), 3))
        rows_sk = [srow(MN["LEBRE_V051"], sk.LEBRE_V051, rmae.LEBRE_V051), srow(MN["M_ONLY"], phs.M_ONLY, phm.M_ONLY),
                   srow(MN["AIRLINE"], phs.AIRLINE, phm.AIRLINE), srow(MN["NLINEAR_ONLINE"], sk.NLINEAR_ONLINE, rmae.NLINEAR_ONLINE),
                   srow(MN["DLINEAR_ONLINE"], sk.DLINEAR_ONLINE, rmae.DLINEAR_ONLINE), srow(MN["HOLT_WINTERS"], sk.HOLT_WINTERS, rmae.HOLT_WINTERS),
                   srow(MN["CHRONOS_BOLT_SMALL"], sk.CHRONOS_BOLT_SMALL, rmae.CHRONOS_BOLT_SMALL), srow(MN["CHRONOS2"], sk.CHRONOS2, rmae.CHRONOS2)]
        out.append(f"""<div class="page-break"></div><h1>9. {toc[8]}</h1>
<h2>9.1 {T("Protocolo e salvaguardas contra viés", "Protocol and safeguards against bias")}</h2>
<ul><li>{T("<strong>Pré-registro.</strong> Hipóteses, critérios, limiares, conjuntos de dados, comparadores e sementes foram escritos antes de qualquer execução, e o documento recebeu um hash SHA-256 registrado. O código do modelo foi congelado por hash, e a execução verifica os dois hashes antes de começar.", "<strong>Pre-registration.</strong> Hypotheses, criteria, thresholds, datasets, comparators and seeds were written before any run, and the document's SHA-256 hash was recorded. The model code was frozen by hash, and the run checks both hashes before starting.")}</li>
<li>{T("<strong>Separação desenvolvimento/avaliação.</strong> Todas as escolhas de projeto foram feitas em dados de desenvolvimento já usados antes; o conjunto de avaliação principal (held-out) é formado por 10 séries que nenhuma versão da LEBRE tinha visto. Sementes aleatórias verificadas como nunca usadas.", "<strong>Development/evaluation separation.</strong> All design choices were made on previously used development data; the main evaluation set (held-out) consists of 10 series that no LEBRE version had seen. Random seeds verified never to have been used.")}</li>
<li>{T("<strong>Avaliação prequencial causal.</strong> A cada passo o modelo prevê e só então vê o valor; as entradas são padronizadas por médias e variâncias acumuladas até o instante anterior; o erro é medido a partir de 30% da série. <strong>NMSE</strong> = erro quadrático médio / variância do trecho de teste. Como todas as comparações usam razões <em>dentro da mesma série</em>, o denominador se cancela: a média geométrica das razões de NMSE é idêntica à das razões de MSE. Reportamos também <em>skill</em> e MAE relativos à persistência (§9.5).", "<strong>Causal prequential evaluation.</strong> At every step the model predicts and only then sees the value; inputs are standardised with means and variances accumulated up to the previous instant; error is measured from 30% of the series onward. <strong>NMSE</strong> = mean squared error / test-segment variance. Since all comparisons use ratios <em>within the same series</em>, the denominator cancels: the geometric mean of NMSE ratios equals that of MSE ratios. We also report <em>skill</em> and MAE relative to persistence (§9.5).")}</li>
<li>{T("<strong>Vantagem dada aos comparadores.</strong> NLinear, DLinear, Holt-Winters e IPNLMS tiveram hiperparâmetros escolhidos por série nos primeiros min(15%, 5000) passos. A LEBRE <em>não</em> foi calibrada. O Holt-Winters online com constantes de uma grade mostrou-se um comparador fraco (pior que a persistência em uma série); por isso a §10 acrescenta um modelo airline ajustado por máxima verossimilhança.", "<strong>Advantage given to comparators.</strong> NLinear, DLinear, Holt-Winters and IPNLMS had hyper-parameters chosen per series on the first min(15%, 5000) steps. LEBRE was <em>not</em> calibrated. Online Holt-Winters with constants from a grid turned out to be a weak comparator (worse than persistence on one series); §10 therefore adds an airline model fitted by maximum likelihood.")}</li>
<li>{T("<strong>Modelos de fundação.</strong> Chronos-Bolt tiny foi avaliado em todo o teste; por custo de CPU, Chronos-Bolt small e Chronos-2 em 1000 pontos igualmente espaçados, e Chronos-2 com covariáveis em 500 (estimativa sem viés do erro médio). Mesmo conjunto de informação (valores até t−1; contexto 512, ou 256 com covariáveis). Séries públicas podem estar no pré-treino desses modelos, o que os favoreceria.", "<strong>Foundation models.</strong> Chronos-Bolt tiny was evaluated on the whole test segment; because of CPU cost, Chronos-Bolt small and Chronos-2 on 1000 evenly spaced points and Chronos-2 with covariates on 500 (unbiased estimate of the mean error). Same information set (values up to t−1; context 512, or 256 with covariates). Public series may be in these models' pre-training data, which would favour them.")}</li>
<li>{T("<strong>Estabilidade.</strong> Cada série foi reprocessada a partir de 10 pontos de partida diferentes (0, 50, …, 450 passos descartados), com a mesma janela de teste.", "<strong>Stability.</strong> Each series was re-run from 10 different start points (0, 50, …, 450 steps dropped) with the same test window.")}</li>
<li>{T("<strong>Versões anteriores da LEBRE.</strong> Elas não entram no ranking. Aparecem apenas como <em>ablações com nome descritivo</em>, quando respondem a uma pergunta de projeto: o <em>especialista estrutural sozinho</em> (versão anterior sem memória) mostra por que a memória é necessária; a <em>variante com janela densa</em> (versão anterior com 96–288 defasagens, ~1000 FP/passo) mostra que a simplificação não perdeu desempenho — era um critério pré-registrado.", "<strong>Earlier LEBRE versions.</strong> They are not in the ranking. They appear only as <em>ablations with descriptive names</em>, when they answer a design question: the <em>structural expert alone</em> (earlier version without memory) shows why the memory is needed; the <em>dense-window variant</em> (earlier version with 96–288 lags, ~1000 FP/step) shows that the simplification did not lose accuracy — it was a pre-registered criterion.")}</li>
<li>{T("<strong>Regra de decisão fixada antes.</strong> A promoção exigia passar em <em>todos</em> os critérios vinculantes. As análises das §10–§11 foram feitas <em>depois</em>, em resposta a uma revisão externa, e estão rotuladas como pós-hoc.", "<strong>Decision rule fixed in advance.</strong> Promotion required passing <em>all</em> binding criteria. The analyses in §10–§11 were done <em>afterwards</em>, in response to an external review, and are labelled post-hoc.")}</li></ul>
<h2>9.2 {T("Conjunto held-out (10 séries reais nunca usadas)", "Held-out set (10 real series never used)")}</h2>
{tbl(["", T("Série", "Series"), T("Frequência", "Frequency"), "d", "s"], rows_ds)}
<p class="small">{T("d = número de variáveis de entrada (todas as variáveis em t−1, incluindo o próprio alvo); s = período declarado. Seis das dez séries têm d = 1, isto é, <strong>nenhuma entrada exógena</strong>: nelas a hipótese estrutural só tem o próprio passado do alvo. Fontes: Operador Nacional do Sistema Elétrico (dados abertos), Banco Central do Brasil (SGS) e Monash Time Series Forecasting Archive (Godahewa et al., 2021).", "d = number of input variables (all variables at t−1, including the target itself); s = declared period. Six of the ten series have d = 1, i.e. <strong>no exogenous input</strong>: there the structural hypothesis only has the target's own past. Sources: Brazilian National Electric System Operator (open data), Central Bank of Brazil (SGS) and the Monash Time Series Forecasting Archive (Godahewa et al., 2021).")}</p>
<div class="no-break"><h2>9.3 {T("Critérios pré-registrados e resultado", "Pre-registered criteria and outcome")}</h2>
{tbl(acc, crit)}</div>
<div class="verdict">{T("DECISÃO PRÉ-REGISTRADA: PROMOVIDA — todos os critérios vinculantes atendidos. (Os critérios comparavam com modelos online leves; §10 mostra comparações mais exigentes feitas depois.)", "PRE-REGISTERED DECISION: PROMOTED — all binding criteria met. (The criteria compared against online lightweight models; §10 shows more demanding comparisons made afterwards.)")}</div>
<h2>9.4 {T("Resultados por série (NMSE, menor é melhor)", "Results per series (NMSE, lower is better)")}</h2>
{tbl(["", T("Série", "Series"), "LEBRE v0.51", T("Só M", "M only"), "NLinear", "DLinear", "Holt-W.", T("Melhor Chronos", "Best Chronos"), T("Persist.", "Persist."), T("Estab.", "Stab."), T("Cobert.", "Cover.")], rows_t)}
<p class="small">{T("Negrito: menor NMSE entre as seis primeiras colunas de modelos. Só M: especialista de memória sozinho (análise pós-hoc). Estab.: máx./mín. do NMSE entre 10 pontos de partida. Cobert.: cobertura empírica do intervalo de 90%.", "Bold: lowest NMSE among the first six model columns. M only: memory expert alone (post-hoc analysis). Stab.: max/min NMSE across 10 start points. Cover.: empirical coverage of the 90% interval.")}</p>
{fig(D["D5"], T("Razão da média geométrica do NMSE em relação ao NLinear no held-out.", "Geometric-mean NMSE ratio relative to NLinear on the held-out set."))}
{tbl([T("Posição", "Position"), T("Modelo", "Model"), T("Classe", "Class"), T("Posto médio", "Mean rank")], rk)}
<p>{T("<strong>Leitura correta do ranking:</strong> a LEBRE v0.51 é o <strong>melhor modelo online leve</strong> avaliado, empatada em posto médio com o Chronos-Bolt small, e fica ~" + n(p2["C3_geo_vs_best_chronos"], 2) + "× atrás do Chronos-2 com custo ~10⁶–10⁷ vezes menor. As versões anteriores da LEBRE foram retiradas do ranking.", "<strong>Correct reading of the ranking:</strong> LEBRE v0.51 is the <strong>best online lightweight model</strong> evaluated, tied in mean rank with Chronos-Bolt small, and is ~" + n(p2["C3_geo_vs_best_chronos"], 2) + "× behind Chronos-2 at ~10⁶–10⁷ times lower cost. Earlier LEBRE versions were removed from the ranking.")}</p>
<h2>9.5 {T("Métricas relativas à persistência", "Metrics relative to persistence")}</h2>
<p>{T("<em>Skill</em> = 1 − MSE/MSE<sub>persistência</sub> (positivo = melhor que repetir o último valor); MAE relativo = MAE/MAE<sub>persistência</sub>. Valores por série resumidos pela mediana.", "<em>Skill</em> = 1 − MSE/MSE<sub>persistence</sub> (positive = better than repeating the last value); relative MAE = MAE/MAE<sub>persistence</sub>. Per-series values summarised by the median.")}</p>
{tbl([T("Modelo", "Model"), T("Skill mediano", "Median skill"), T("Séries com skill > 0", "Series with skill > 0"), T("MAE relativo mediano", "Median relative MAE")], rows_sk)}
<p class="small">{T("Nas duas séries de câmbio, nenhum modelo supera a persistência com folga: o câmbio diário se comporta como passeio aleatório.", "On the two exchange-rate series no model beats persistence by a margin: daily exchange rates behave like a random walk.")}</p>
<h2>9.6 {T("Suíte interna (sistemas guiados por entradas)", "Internal suite (input-driven systems)")}</h2>
<p>{T("14 processos sintéticos com estrutura conhecida — atrasos exatos e múltiplos, estados latentes, quiescência, mudanças de regime, estrutura redundante e um controle não linear; 30 sementes novas por tarefa:", "14 synthetic processes with known structure — exact and multiple delays, latent states, quiescence, regime switches, redundant structure and a non-linear control; 30 fresh seeds per task:")}</p>
{tbl([T("Variante", "Variant"), "NMSE", T("FP/passo (média)", "FP/step (mean)"), T("FP pico", "FP peak"), T("Cobertura", "Coverage"), T("Estrutura exata", "Exact structure")],
     [(MN["LEBRE_V051"], n(I.loc["V051", "nmse"], 4), n(I.loc["V051", "fp"], 1), n(I.loc["V051", "peak"], 0), n(I.loc["V051", "cov"], 3), f'{n(100 * I.loc["V051", "struct"], 1)}%'),
      (T("Especialista estrutural sozinho", "Structural expert alone"), n(I.loc["V045", "nmse"], 4), n(I.loc["V045", "fp"], 1), n(I.loc["V045", "peak"], 0), n(I.loc["V045", "cov"], 3), f'{n(100 * I.loc["V045", "struct"], 1)}%'),
      (T("Variante com janela densa", "Dense-window variant"), n(I.loc["V05", "nmse"], 4), n(I.loc["V05", "fp"], 1), n(I.loc["V05", "peak"], 0), n(I.loc["V05", "cov"], 3), f'{n(100 * I.loc["V05", "struct"], 1)}%')])}
<p>{T("Aqui a LEBRE iguala o especialista estrutural sozinho e recupera a estrutura correta em ~91% das verificações. A memória sozinha <strong>não serve</strong> nesses sistemas (NMSE ≈ 1,0 nos dados de desenvolvimento). É nesta suíte — sintética — que a parte estrutural se paga.", "Here LEBRE matches the structural expert alone and recovers the correct structure in ~91% of the checks. The memory alone is <strong>useless</strong> on these systems (NMSE ≈ 1.0 on development data). It is on this suite — synthetic — that the structural part pays off.")}</p>
<p>{T(f"<strong>Verificações secundárias</strong> (conjuntos já vistos em etapas anteriores): num segundo conjunto de 10 séries (5 brasileiras), {n(p3['heldout_v05']['geo_vs_NLinear'], 2)}× o NLinear e {n(p3['heldout_v05']['geo_vs_best_chronos'], 2)}× o melhor Chronos; num benchmark de 10 tarefas reais com 36 modelos (filtros adaptativos, redes e reservatórios online, árvores online, lineares modernos e modelos de fundação), {n(p3['bench04']['geo_vs_NLinear'], 2)}× o NLinear, {n(p3['bench04']['geo_vs_best_chronos'], 2)}× o melhor Chronos e estabilidade máxima de {n(p3['bench04']['instab_max'], 2)}.",
f"<strong>Secondary checks</strong> (sets seen in earlier stages): on a second set of 10 series (5 Brazilian), {n(p3['heldout_v05']['geo_vs_NLinear'], 2)}× NLinear and {n(p3['heldout_v05']['geo_vs_best_chronos'], 2)}× the best Chronos; on a benchmark of 10 real tasks with 36 models (adaptive filters, online networks and reservoirs, online trees, modern linear models and foundation models), {n(p3['bench04']['geo_vs_NLinear'], 2)}× NLinear, {n(p3['bench04']['geo_vs_best_chronos'], 2)}× the best Chronos and maximum instability {n(p3['bench04']['instab_max'], 2)}.")}</p>
<h2>9.7 {T("Evidência de projeto (ablações em dados de desenvolvimento)", "Design evidence (ablations on development data)")}</h2>
<p>{T("13 séries reais já usadas e a suíte interna com sementes de desenvolvimento. \"Séries reais\" = razão geométrica do NMSE contra um NLinear online com janela densa.", "13 previously used real series and the internal suite with development seeds. \"Real series\" = geometric NMSE ratio against an online NLinear with a dense window.")}</p>
{tbl([T("Variante", "Variant"), T("Séries reais", "Real series"), T("Interno", "Internal"), T("Conclusão", "Conclusion")],
     [(T("só S (especialista estrutural sozinho)", "S only (structural expert alone)"), "2,07" if P else "2.07", "0,221" if P else "0.221", T("sem M, não é competitivo em séries reais", "without M, not competitive on real series")),
      (T("só M (memória sozinha)", "M only (memory alone)"), "0,96" if P else "0.96", "1,008" if P else "1.008", T("sem S, inútil em sistemas guiados por entradas", "without S, useless on input-driven systems")),
      (T("M sem perfil sazonal G", "M without seasonal profile G"), "1,12" if P else "1.12", "—", T("G é o ingrediente decisivo de M", "G is M's decisive ingredient")),
      (T("cascata M → S (sem combinador)", "cascade M → S (no combiner)"), "0,97" if P else "0.97", "0,304" if P else "0.304", T("combinador necessário", "combiner needed")),
      (T("S → M sobre o resíduo de S", "S → M on S's residual"), "1,47" if P else "1.47", "0,255" if P else "0.255", T("idem", "idem")),
      (T("combinação por regressão", "regression combination"), "0,94" if P else "0.94", "0,240" if P else "0.240", T("média dinâmica preferível", "dynamic averaging preferred")),
      (T("sem dormência de S", "without S dormancy"), "0,98" if P else "0.98", "0,220" if P else "0.220", T("dormência: −25 FP sem perda", "dormancy: −25 FP, no loss")),
      ("<strong>LEBRE v0.51</strong>", "<strong>0,98</strong>" if P else "<strong>0.98</strong>", "<strong>0,220</strong>" if P else "<strong>0.220</strong>", "—")])}
<p class="small">{T("Observe que \"só M\" (0,96) é ligeiramente melhor que a v0.51 (0,98) nas séries reais de desenvolvimento: o especialista estrutural não ajuda nelas. Ele só é mantido porque, sem ele, o modelo falha nos sistemas guiados por entradas.", "Note that \"M only\" (0.96) is slightly better than v0.51 (0.98) on the real development series: the structural expert does not help there. It is kept only because, without it, the model fails on input-driven systems.")}</p>""")

        # ------------------------------------------------------------ 10 LEBRE vs M only and strong classical baselines
        ws = N["ph_ws"].set_index(["src", "task"])
        pn = ph.pivot_table(index=["src", "task"], columns="arm", values="nmse")
        rows_m = []
        for t in order:
            q = pn.loc[("held", t)]
            w = ws.loc[("held", t)]
            fmt = lambda v: "—" if (v != v or v > 1) else n(v, 4)
            rows_m.append([qn(t), n(q.V051, 4), n(q.M_ONLY, 4), fmt(q.AIRLINE), fmt(q.ETS), fmt(q.RLS5), n(w.wS_mean, 3), n(w.wS_max, 3), f"{n(100 * w['frac_wS_gt_0.5'], 0)}%"])
        ssum = N["ph_summ"]
        def sline(a):
            x, y = ssum[("held", a)], ssum[("held05", a)]
            return [n(x["geo"], 3), f"{x['n']}/10", n(y["geo"], 3), f"{y['n']}/10"]
        rows_s = [[T("Só M (memória sozinha)", "M only (memory alone)")] + sline("M_ONLY"),
                  [T("Airline SARIMA(0,1,1)(0,1,1)s por MLE", "Airline SARIMA(0,1,1)(0,1,1)s by MLE")] + sline("AIRLINE"),
                  [T("ETS aditivo por MLE (AIC)", "Additive ETS by MLE (AIC)")] + sline("ETS"),
                  [T("RLS (λ = 0,999) nas 5 features de M", "RLS (λ = 0.999) on M's 5 features")] + sline("RLS5")]
        out.append(f"""<div class="page-break"></div><h1>10. {toc[9]}</h1>
<p>{T("Esta seção responde a uma revisão externa. Todas as análises são <strong>pós-hoc</strong> (feitas depois do pré-registro) e cobrem os dois conjuntos held-out (20 séries).", "This section answers an external review. All analyses are <strong>post-hoc</strong> (done after pre-registration) and cover both held-out sets (20 series).")}</p>
<h2>10.1 {T("Quanto do resultado vem da memória", "How much of the result comes from the memory")}</h2>
{tbl(["", "LEBRE v0.51", T("Só M", "M only"), T("Airline (MLE)", "Airline (MLE)"), "ETS (MLE)", "RLS", T("w<sub>S</sub> médio", "mean w<sub>S</sub>"), T("w<sub>S</sub> máx.", "max w<sub>S</sub>"), T("tempo com w<sub>S</sub> > 0,5", "time with w<sub>S</sub> > 0.5")], rows_m)}
<p class="small">{T("NMSE no held-out principal. w<sub>S</sub>: peso do especialista estrutural ao longo do trecho de teste. \"—\": o método falhou (memória insuficiente para o airline com s = 144; divergência do RLS ou do ETS).", "NMSE on the main held-out set. w<sub>S</sub>: weight of the structural expert along the test segment. \"—\": the method failed (out of memory for the airline with s = 144; RLS or ETS divergence).")}</p>
<ul><li>{T(f"<strong>A LEBRE e a memória sozinha dão resultado idêntico em {ssum[('held', 'M_ONLY')]['same']} de 10 séries</strong> (w<sub>S</sub> ≈ 0 durante todo o teste). A razão geométrica só M / LEBRE é {n(ssum[('held', 'M_ONLY')]['geo'], 3)} no held-out principal e {n(ssum[('held05', 'M_ONLY')]['geo'], 3)} no segundo conjunto.", f"<strong>LEBRE and the memory alone give identical results on {ssum[('held', 'M_ONLY')]['same']} of 10 series</strong> (w<sub>S</sub> ≈ 0 throughout the test). The geometric ratio M only / LEBRE is {n(ssum[('held', 'M_ONLY')]['geo'], 3)} on the main held-out set and {n(ssum[('held05', 'M_ONLY')]['geo'], 3)} on the second set.")}</li>
<li>{T("O especialista estrutural só ganha peso no <strong>câmbio</strong> e na <strong>qualidade do ar</strong>, onde melhora o resultado da memória (ex.: 0,101 contra 0,138 na qualidade do ar). Nas quatro séries do ONS com d = 6 entradas, w<sub>S</sub> nunca passa de ~0,05: as outras variáveis do balanço energético, observadas em t−1, não acrescentam informação útil sobre o alvo além do seu próprio passado.", "The structural expert only gains weight on <strong>exchange rates</strong> and <strong>air quality</strong>, where it improves on the memory (e.g. 0.101 vs 0.138 on air quality). On the four ONS series with d = 6 inputs, w<sub>S</sub> never exceeds ~0.05: the other energy-balance variables, observed at t−1, add no useful information about the target beyond its own past.")}</li>
<li>{T("<strong>Conclusão:</strong> nas séries reais avaliadas, o desempenho da LEBRE é essencialmente o do especialista de memória, que é uma forma online do modelo airline / Holt-Winters com pesos aprendidos por NLMS.", "<strong>Conclusion:</strong> on the real series evaluated, LEBRE's accuracy is essentially that of the memory expert, which is an online form of the airline / Holt-Winters model with weights learned by NLMS.")}</li></ul>
<h2>10.2 {T("Comparadores clássicos fortes", "Strong classical baselines")}</h2>
{tbl([T("Modelo (razão geométrica contra a LEBRE v0.51)", "Model (geometric ratio vs LEBRE v0.51)"), T("Held-out principal", "Main held-out"), T("séries válidas", "valid series"), T("Segundo conjunto", "Second set"), T("séries válidas", "valid series")], rows_s)}
<ul><li>{T(f"<strong>O modelo airline ajustado por máxima verossimilhança é mais preciso que a LEBRE</strong> (razões {n(ssum[('held', 'AIRLINE')]['geo'], 3)} e {n(ssum[('held05', 'AIRLINE')]['geo'], 3)}). Ele recebeu a mesma vantagem dos outros comparadores: os parâmetros θ e Θ foram estimados nos primeiros min(15%, 5000) passos de cada série e depois mantidos fixos. Em forma recursiva, a previsão airline custa poucas dezenas de operações por passo. O que a LEBRE oferece em troca é não precisar desse ajuste por série, funcionar também em sistemas guiados por entradas, produzir intervalos calibrados e registrar a estrutura.", f"<strong>The airline model fitted by maximum likelihood is more accurate than LEBRE</strong> (ratios {n(ssum[('held', 'AIRLINE')]['geo'], 3)} and {n(ssum[('held05', 'AIRLINE')]['geo'], 3)}). It received the same advantage as the other comparators: θ and Θ were estimated on the first min(15%, 5000) steps of each series and then kept fixed. In recursive form, the airline forecast costs a few dozen operations per step. What LEBRE offers in exchange is not needing this per-series fit, also working on input-driven systems, producing calibrated intervals and logging the structure.")}</li>
<li>{T("O ETS aditivo ajustado por máxima verossimilhança foi <strong>pior</strong> que a LEBRE e divergiu numa série: não é um comparador robusto nesse protocolo.", "Additive ETS fitted by maximum likelihood was <strong>worse</strong> than LEBRE and diverged on one series: it is not a robust comparator in this protocol.")}</li>
<li>{T("O RLS com esquecimento sobre as mesmas 5 features foi ~7% mais preciso quando estável, mas <strong>divergiu nas séries longas</strong> (50 000 passos). Isso mostra que o mérito está principalmente na escolha das features; o NLMS troca um pouco de precisão por estabilidade numérica e custo O(k).", "RLS with forgetting on the same 5 features was ~7% more accurate when stable, but <strong>diverged on the long series</strong> (50,000 steps). This shows that the merit lies mainly in the choice of features; NLMS trades some accuracy for numerical stability and O(k) cost.")}</li></ul>
<h2>10.3 {T("O que diferencia a LEBRE da memória sozinha", "What distinguishes LEBRE from the memory alone")}</h2>
{tbl(["", T("Só M", "M only"), "LEBRE v0.51"],
     [(T("Precisão em séries reais sazonais", "Accuracy on real seasonal series"), T("igual", "same"), T("igual (≤ 3% melhor, graças a 2 séries)", "same (≤ 3% better, thanks to 2 series)")),
      (T("Sistemas guiados por entradas (atrasos, estados ocultos)", "Input-driven systems (delays, hidden states)"), T("falha (NMSE ≈ 1)", "fails (NMSE ≈ 1)"), T("funciona (NMSE 0,215)", "works (NMSE 0.215)") if P else "works (NMSE 0.215)"),
      (T("Explicação", "Explanation"), T("aditiva, com 5 parcelas fixas", "additive, 5 fixed terms"), T("aditiva, com estrutura selecionada por evidência e nomeada", "additive, with evidence-selected, named structure")),
      (T("Registro de mudanças de estrutura", "Log of structural changes"), T("não", "no"), T("sim (promoções e perdas de utilidade)", "yes (promotions and loss-of-usefulness signals)")),
      (T("Peso que indica a hipótese vigente", "Weight indicating the current hypothesis"), T("não", "no"), "w<sub>S</sub>"),
      (T("Custo por passo", "Cost per step"), f"~{n(N['m_cost']['Q1_ONS_Carga_SIN_2019_20'], 0)} FP", f"~{n(ch.loc['LEBRE_V051', 'fp'], 0)} FP")])}
<p>{T("<strong>Posicionamento honesto.</strong> Para quem só precisa prever séries sazonais sem entradas relevantes, a memória sozinha — ou um modelo airline ajustado por série — é suficiente e mais barata. A LEBRE se justifica quando o mesmo previsor, sem ajuste por série, precisa servir tanto a séries sazonais quanto a sistemas guiados por entradas, e quando a estrutura descoberta e o seu registro têm valor operacional. Essa última parte ainda precisa de evidência em séries reais genuinamente guiadas por entradas (§12).", "<strong>Honest positioning.</strong> If one only needs to forecast seasonal series without relevant inputs, the memory alone — or an airline model fitted per series — is enough and cheaper. LEBRE is justified when the same forecaster, with no per-series tuning, must serve both seasonal series and input-driven systems, and when the discovered structure and its log have operational value. That last part still needs evidence on real, genuinely input-driven series (§12).")}</p>""")

        # ------------------------------------------------------------ 11 statistical guarantees in practice
        nd = N["ph_null"].groupby("kind")[["promotions", "evictions_true_atom", "steps"]].sum()
        out.append(f"""<h1>11. {toc[10]}</h1>
<p>{T("As garantias da §5.3 valem sob hipóteses idealizadas e por teste. Para saber o que acontece em fluxos longos, medimos (pós-hoc) o comportamento do especialista estrutural em fluxos de 100 000 passos, 10 sementes cada:", "The guarantees in §5.3 hold under idealised assumptions and per test. To see what happens on long streams, we measured (post-hoc) the structural expert on streams of 100,000 steps, 10 seeds each:")}</p>
{tbl([T("Fluxo", "Stream"), T("Passos totais", "Total steps"), T("Promoções falsas", "False promotions"), T("Remoções do átomo verdadeiro", "Evictions of the true atom")],
     [(T("nulo gaussiano (entradas independentes do alvo)", "Gaussian null (inputs independent of the target)"), f"{int(nd.loc['null_gauss', 'steps']):,}".replace(",", "." if P else ","), str(int(nd.loc["null_gauss", "promotions"])), "—"),
      (T("nulo com caudas pesadas (t de Student, 3 g.l.)", "heavy-tailed null (Student t, 3 d.o.f.)"), f"{int(nd.loc['null_t3', 'steps']):,}".replace(",", "." if P else ","), str(int(nd.loc["null_t3", "promotions"])), "—"),
      (T("estrutura verdadeira estacionária (y = 0,8·x1(t−3) + ruído)", "stationary true structure (y = 0.8·x1(t−3) + noise)"), f"{int(nd.loc['true_atom', 'steps']):,}".replace(",", "." if P else ","), "—", str(int(nd.loc["true_atom", "evictions_true_atom"])))])}
<ul><li>{T("<strong>Promoções:</strong> nenhuma promoção falsa em 2 milhões de passos nulos. O controle é formalmente por episódio, mas o acúmulo em fluxos longos foi desprezível nestes testes.", "<strong>Promotions:</strong> no false promotion in 2 million null steps. The control is formally per episode, but accumulation over long streams was negligible in these tests.")}</li>
<li>{T(f"<strong>Remoções:</strong> num fluxo estacionário, o átomo verdadeiro foi removido {int(nd.loc['true_atom', 'evictions_true_atom'])} vezes em 1 milhão de passos (e depois repromovido). Por causa do aluguel de parcimônia, não há garantia formal de taxa de alarme falso: as remoções devem ser lidas como <em>sinais de perda de utilidade</em>, não como alarmes de mudança com erro controlado.", f"<strong>Evictions:</strong> on a stationary stream the true atom was evicted {int(nd.loc['true_atom', 'evictions_true_atom'])} times in 1 million steps (and later re-promoted). Because of the parsimony rent there is no formal false-alarm-rate guarantee: evictions should be read as <em>loss-of-usefulness signals</em>, not as change alarms with a controlled error.")}</li></ul>""")

        # ------------------------------------------------------------ 12 what it demonstrates
        out.append(f"""<div class="page-break"></div><h1>12. {toc[11]}</h1>
<p>{T("Este documento contém, na prática, <strong>dois resultados distintos</strong>, e é importante não confundi-los:", "This document contains, in practice, <strong>two distinct results</strong>, and it is important not to confuse them:")}</p>
<h2>{T("Resultado 1 — um previsor online barato, estável e bem avaliado", "Result 1 — a cheap, stable, well-evaluated online forecaster")}</h2>
<p>{T("Demonstrado com rigor em dados reais: pré-registro, held-out nunca visto, comparadores calibrados, estabilidade e cobertura. O desempenho vem principalmente do especialista de memória, construído com peças clássicas (modelo airline, suavização exponencial, NLMS, média dinâmica de modelos). O valor é de <strong>engenharia</strong>: uma combinação específica, sem ajuste por série, dimensionada para ~120 operações por passo e com intervalos calibrados. <strong>Não há novidade científica</strong> nesta parte, e um modelo airline ajustado série a série é um pouco mais preciso.", "Rigorously demonstrated on real data: pre-registration, never-seen held-out set, calibrated comparators, stability and coverage. The accuracy comes mainly from the memory expert, built from classical pieces (airline model, exponential smoothing, NLMS, dynamic model averaging). The value is <strong>engineering</strong>: a specific combination, with no per-series tuning, sized for ~120 operations per step and with calibrated intervals. <strong>There is no scientific novelty</strong> in this part, and an airline model fitted series by series is somewhat more accurate.")}</p>
<h2>{T("Resultado 2 — descoberta estrutural online com testes estatísticos", "Result 2 — online structure discovery with statistical tests")}</h2>
<p>{T("O especialista estrutural decide, por testes baseados em martingales e portões previsíveis (silêncio, quarentena, dormência), quais atrasos e estados ocultos entram no modelo. É a parte mais interessante do ponto de vista científico e conecta-se com a área de inferência sempre válida (Ramdas et al., 2023). <strong>Hoje ela só tem evidência em processos sintéticos</strong>: nas séries reais avaliadas, o especialista estrutural quase nunca é escolhido. Para defendê-la seriam necessárias séries reais genuinamente guiadas por entradas — processos industriais, sistemas hidráulicos com vazão a montante, identificação de sistemas.", "The structural expert decides, by martingale-based tests and predictable gates (silence, quarantine, dormancy), which delays and hidden states enter the model. It is the most interesting part scientifically and connects to the area of anytime-valid inference (Ramdas et al., 2023). <strong>Today it has evidence only on synthetic processes</strong>: on the real series evaluated, the structural expert is almost never selected. Defending it would require real, genuinely input-driven series — industrial processes, hydraulic systems with upstream flow, system identification.")}</p>
<div class="alert alert-warning">{T("<strong>Consequência:</strong> a afirmação \"a LEBRE é competitiva em séries reais\" é verdadeira, mas deve ser atribuída ao especialista de memória. A afirmação \"a descoberta estrutural da LEBRE funciona em dados reais\" <strong>ainda não está demonstrada</strong>.", "<strong>Consequence:</strong> the statement \"LEBRE is competitive on real series\" is true, but it should be credited to the memory expert. The statement \"LEBRE's structure discovery works on real data\" is <strong>not yet demonstrated</strong>.")}</div>""")

        # ------------------------------------------------------------ 13 evolution
        ev = [(T("Organização original", "Original organisation"), T("Caminho-base, atrasos esparsos, estado latente, ciclo de vida com probação em sombra.", "Base path, sparse delays, latent state, lifecycle with shadow probation."), T("referência canônica congelada", "frozen canonical reference")),
              (T("Decisões por testes estatísticos", "Decisions by statistical tests"), T("Toda decisão estrutural vira teste (martingale de mistura, CUSUM); latente em forma de inovações de Kalman; ≤ 100 FP.", "Every structural decision becomes a test (mixture martingale, CUSUM); latent in Kalman innovations form; ≤ 100 FP."), T("estável, mas 2–3× pior que modelos modernos em séries sazonais", "stable, but 2–3× worse than modern models on seasonal series")),
              (T("Especialista estrutural sozinho", "Structural expert alone"), T("Aprendizado proporcional, intervalos, explicação exata, guarda de contrato de entrada.", "Proportionate learning, intervals, exact explanation, input-contract guard."), T("instável conforme o ponto de partida; ~2,6× o NLinear em dados reais", "start-point-dependent instability; ~2.6× NLinear on real data")),
              (T("Variante com janela densa", "Dense-window variant"), T("Três especialistas, janela de 96–288 defasagens.", "Three experts, window of 96–288 lags."), T("competitiva e estável, mas ~1000 FP/passo", "competitive and stable, but ~1000 FP/step")),
              ("v0.51", T("Dois especialistas mínimos (estrutural + memória airline) e média dinâmica de modelos.", "Two minimal experts (structural + airline memory) and dynamic model averaging."), T("~120 FP/passo; desempenho vindo sobretudo da memória", "~120 FP/step; accuracy coming mainly from the memory"))]
        out.append(f"""<h1>13. {toc[12]}</h1>
<p>{T("As versões anteriores são citadas apenas para explicar como se chegou à arquitetura atual; o leitor não precisa conhecê-las.", "Earlier versions are mentioned only to explain how the current architecture was reached; the reader does not need to know them.")}</p>
{tbl([T("Etapa", "Stage"), T("Ideia central", "Central idea"), T("Resultado", "Outcome")], ev)}
<p>{T("<strong>Lições.</strong> (1) Em séries reais sazonais, o desempenho depende de memória do próprio alvo expressa relativa ao último valor; a hipótese estrutural esparsa, sozinha, não basta. (2) Aprender o nível pelo termo de viés torna as decisões estruturais iniciais dependentes do ponto de partida. (3) Uma memória bem especificada, com 5 números aprendidos, supera uma janela densa com centenas de pesos aprendidos online — em linha com as competições M: métodos estatísticos simples e bem especificados são difíceis de superar (Makridakis et al., 2020). (4) Um modelo clássico ajustado série a série continua sendo uma referência exigente.", "<strong>Lessons.</strong> (1) On real seasonal series, accuracy depends on memory of the target itself expressed relative to the last value; the sparse structural hypothesis alone is not enough. (2) Learning the level through the bias term makes early structural decisions depend on the start point. (3) A well-specified memory with 5 learned numbers beats a dense window with hundreds of weights learned online — in line with the M competitions: simple, well-specified statistical methods are hard to beat (Makridakis et al., 2020). (4) A classical model fitted series by series remains a demanding reference.")}</p>""")

        # ------------------------------------------------------------ 14 limits
        lim = [T("A LEBRE não pretende ser o modelo mais preciso: Chronos-2 é ~1,37× melhor e um modelo airline ajustado série a série é ~5–10% melhor.", "LEBRE does not aim to be the most accurate model: Chronos-2 is ~1.37× better and an airline model fitted series by series is ~5–10% better."),
               T("Nas séries reais avaliadas, o resultado vem quase todo do especialista de memória; a descoberta estrutural só tem evidência em dados sintéticos.", "On the real series evaluated, the result comes almost entirely from the memory expert; structure discovery has evidence only on synthetic data."),
               T("O orçamento de 150 FP/passo vale para até ~6 entradas; cada entrada adicional custa ~8 FP. A execução em microcontroladores não foi verificada.", "The 150 FP/step budget holds for up to ~6 inputs; every extra input costs ~8 FP. Execution on microcontrollers was not verified."),
               T("O controle de erro das promoções vale por episódio de teste; as remoções não têm taxa de alarme falso garantida.", "Promotion error control holds per test episode; evictions have no guaranteed false-alarm rate."),
               T("A classe é linear nos parâmetros; previsão de um passo à frente; cobertura do intervalo de longo prazo, não condicional.", "The class is linear in the parameters; one-step-ahead forecasting; long-run, not conditional, interval coverage."),
               T("A decomposição exata, sozinha, não é diferencial: qualquer modelo linear aditivo a possui.", "Exact decomposition alone is not a differentiator: any linear additive model has it."),
               T("Não afirmamos: estado da arte, novidade científica, causalidade física, eficiência energética (FP não é energia) nem cobertura condicional.", "We do not claim: state of the art, scientific novelty, physical causality, energy efficiency (FP is not energy) or conditional coverage.")]
        out.append(f"""<h1>14. {toc[13]}</h1><ul>{''.join(f'<li>{x}</li>' for x in lim)}</ul>""")

        # ------------------------------------------------------------ 15 parameters
        par = [("μ (S)", "0,1" if P else "0.1", T("passo do NLMS do especialista estrutural", "NLMS step of the structural expert")),
               ("μ (M)", "0,05" if P else "0.05", T("passo do NLMS da memória", "NLMS step of the memory")),
               ("a", "0,1" if P else "0.1", T("perfil sazonal (Θ = 0,9 no modelo airline)", "seasonal profile (Θ = 0.9 in the airline model)")),
               (T("fator da média", "mean factor"), "0,01" if P else "0.01", T("média exponencial para a reversão à média", "exponential mean for mean reversion")),
               ("η", "1/2", T("derivado da verossimilhança gaussiana", "derived from the Gaussian likelihood")),
               ("λ", "0,99" if P else "0.99", T("esquecimento do combinador e do σ̂² combinado (~100 passos)", "forgetting of the combiner and combined σ̂² (~100 steps)")),
               (T("limiar de dormência", "dormancy threshold"), "0,01" if P else "0.01", T("peso abaixo do qual a evidência de S pausa", "weight below which S's evidence pauses")),
               ("L", "32", T("atraso máximo dos candidatos", "maximum candidate delay")),
               ("M_max", "4", T("orçamento de átomos estruturais", "structural atom budget")),
               ("α", "0,05" if P else "0.05", T("taxa de promoção falsa por episódio (limiar log(p/α))", "false-promotion rate per episode (threshold log(p/α))")),
               ("ARL", "6000", T("h = log ARL (garantia só sem aluguel)", "h = log ARL (guarantee only without rent)")),
               ("T_idle", "500", T("aluguel de parcimônia r = h/T_idle", "parsimony rent r = h/T_idle")),
               (T("polos", "poles"), "{0; 0,5; 0,8; 0,95}" if P else "{0, 0.5, 0.8, 0.95}", T("banco do estado latente", "latent-state bank")),
               (T("recorte", "clip"), "±8", T("contrato de entrada (P6)", "input contract (P6)")),
               (T("excitação", "excitation"), "10%", T("potência mínima para acumular evidência (P4)", "minimum power to accrue evidence (P4)")),
               (T("intervalo", "interval"), "α = 0,1; γ = 0,1" if P else "α = 0.1; γ = 0.1", T("cobertura alvo 90%; passo do rastreador", "target coverage 90%; tracker step")),
               (T("cadência", "cadence"), "8", T("passos entre recálculos de raiz, inversa, exp e quantil", "steps between square root, inverse, exp and quantile recomputation")),
               ("s", T("do ambiente", "from environment"), T("período de amostragem declarado (único dado externo)", "declared sampling period (only external information)"))]
        out.append(f"""<div class="page-break"></div><h1>15. {toc[14]}</h1>
<p>{T("Todos os valores são constantes do projeto, iguais para todas as séries; nenhum foi ajustado nos dados de avaliação.", "All values are design constants, identical for every series; none was tuned on the evaluation data.")}</p>
{tbl([T("Parâmetro", "Parameter"), T("Valor", "Value"), T("Papel", "Role")], par)}""")

        # ------------------------------------------------------------ 16 references
        out.append(f"""<h1>16. {toc[15]}</h1><ol class="refs">{''.join(f'<li>{r}</li>' for r in REFS)}</ol>""")
''')

# the tail block replaced everything from §9 up to the PT math fix; keep the fix and return
open(p, "w", encoding="utf-8").write(s)
print("ok")
